# Generated by Django 4.0.3 on 2022-11-20 23:01

import Users.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id_city', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Ciudad')),
                ('description', models.CharField(blank=True, max_length=45, null=True, verbose_name='Descripcion')),
                ('zip_code', models.CharField(max_length=6, verbose_name='Codigo postal')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificacion')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
                'db_table': 'city',
                'ordering': ['id_city'],
            },
        ),
        migrations.CreateModel(
            name='TypeOfDocument',
            fields=[
                ('id_type_of_document', models.AutoField(primary_key=True, serialize=False, verbose_name='Id tipo de documento')),
                ('description', models.CharField(max_length=45, verbose_name='Descripcion')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificacion')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Tipo de documento',
                'verbose_name_plural': 'Tipos de documento',
                'db_table': 'type_of_document',
                'ordering': ['id_type_of_document'],
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id_user', models.AutoField(primary_key=True, serialize=False, verbose_name='Id usuario')),
                ('first_name', models.CharField(max_length=45, null=True, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=45, null=True, verbose_name='Apellido')),
                ('email', models.CharField(max_length=55, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Correo')),
                ('number_document', models.CharField(max_length=12, null=True, verbose_name='Numero de documento')),
                ('main_address', models.CharField(max_length=70, null=True, verbose_name='Direccion')),
                ('neighborhood', models.CharField(max_length=30, null=True, verbose_name='Barrio/Localidad')),
                ('phone_number', models.CharField(max_length=15, null=True, verbose_name='Numero de telefono')),
                ('gender', models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer'), ('Prefiero no decirlo', 'Prefiero no decirlo')], default='Prefiero no decirlo', max_length=19, null=True, verbose_name='Genero')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificacion')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Administrador')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.city', verbose_name='Ciudad')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('type_of_document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.typeofdocument', verbose_name='Tipo de documento')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'user',
                'ordering': ['id_user'],
            },
            managers=[
                ('objects', Users.models.UserManager()),
            ],
        ),
    ]
