# Generated by Django 4.0.3 on 2022-11-20 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Carts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingDocument',
            fields=[
                ('id_accounting_document', models.AutoField(primary_key=True, serialize=False, verbose_name='Id documento contable')),
                ('number_accounting_document', models.CharField(max_length=10, unique=True, verbose_name='Numero documento contable')),
                ('accounting_document_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha documento contable')),
            ],
            options={
                'verbose_name': 'Documento contable',
                'verbose_name_plural': 'Documentos contables',
                'db_table': 'accounting_document',
                'ordering': ['id_accounting_document'],
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id_address', models.AutoField(primary_key=True, serialize=False, verbose_name='Id direccion')),
                ('address', models.CharField(max_length=70, verbose_name='Direccion')),
                ('neighborhood', models.CharField(max_length=50, verbose_name='Barrio/Localidad')),
                ('default', models.BooleanField(default=False, verbose_name='Direccion principal')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificacion')),
            ],
            options={
                'verbose_name': 'Direccion de envio',
                'verbose_name_plural': 'Direcciones de envio',
                'db_table': 'address',
                'ordering': ['id_address'],
            },
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id_payment_type', models.AutoField(primary_key=True, serialize=False, verbose_name='Id tipo de pago')),
                ('description', models.CharField(max_length=45, verbose_name='Descripcion')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificacion')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Tipo de pago',
                'verbose_name_plural': 'Tipos de pagos',
                'db_table': 'payment_type',
                'ordering': ['id_payment_type'],
            },
        ),
        migrations.CreateModel(
            name='TypeAccountingDocument',
            fields=[
                ('id_type_accounting_document', models.AutoField(primary_key=True, serialize=False, verbose_name='Id tipo documento contable')),
                ('nature', models.CharField(max_length=45, verbose_name='Naturaleza')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificacion')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Tipo documento contable',
                'verbose_name_plural': 'Tipos documentos contables',
                'db_table': 'type_accounting_document',
                'ordering': ['id_type_accounting_document'],
            },
        ),
        migrations.CreateModel(
            name='TypeOfDelivery',
            fields=[
                ('id_type_of_delivery', models.AutoField(primary_key=True, serialize=False, verbose_name='Id tipo de entrega')),
                ('description', models.CharField(max_length=45, verbose_name='Descripcion')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificacion')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Tipo de entrega',
                'verbose_name_plural': 'Tipos de entregas',
                'db_table': 'type_of_delivery',
                'ordering': ['id_type_of_delivery'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id_order', models.AutoField(primary_key=True, serialize=False, verbose_name='Id orden')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha pedido')),
                ('state', models.CharField(choices=[('Creado', 'Creado'), ('Pagado', 'Pagado'), ('Completado', 'Completado'), ('Cancelado', 'Cancelado')], default='Creado', max_length=10, verbose_name='Estado')),
                ('total', models.PositiveIntegerField(default=0, verbose_name='Total')),
                ('shipping_total', models.PositiveIntegerField(default=0, verbose_name='Costo envio')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificacion')),
                ('identifier', models.CharField(max_length=100, unique=True, verbose_name='Identificador unico')),
                ('send_bill', models.BooleanField(default=False, verbose_name='Factura enviada')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Orders.address', verbose_name='Direccion')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Carts.cart', verbose_name='Carrito')),
                ('payment_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Orders.paymenttype', verbose_name='Tipo de pago')),
                ('type_accounting_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Orders.typeaccountingdocument', verbose_name='Tipo documento contable')),
                ('type_of_delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Orders.typeofdelivery', verbose_name='Tipo de entrega')),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Ordenes',
                'db_table': 'order',
                'ordering': ['id_order'],
            },
        ),
    ]
